# Generated by Django 6.0.8 on 2026-08-07 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(default='auto', max_length=10, verbose_name='idioma origen')),
                ('target_language', models.CharField(max_length=10, verbose_name='idioma destino')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'En proceso'), ('completed', 'Completada'), ('partial', 'Completa con errores'), ('failed', 'Fallida')], default='pending', max_length=10, verbose_name='estado')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='páginas totales')),
                ('processed_pages', models.PositiveIntegerField(default=0, verbose_name='páginas procesadas')),
                ('failed_pages', models.PositiveIntegerField(default=0, verbose_name='páginas fallidas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='documents.document', verbose_name='documento')),
            ],
            options={
                'verbose_name': 'traducción',
                'verbose_name_plural': 'traducciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='número de página')),
                ('original_content', models.TextField(verbose_name='contenido original')),
                ('translated_content', models.TextField(blank=True, default='', verbose_name='contenido traducido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida')], default='pending', max_length=10, verbose_name='estado')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='translations.translation', verbose_name='traducción')),
            ],
            options={
                'verbose_name': 'página de traducción',
                'verbose_name_plural': 'páginas de traducción',
                'ordering': ['page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['document', 'status'], name='translations_doc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('document', 'target_language'), name='translations_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='translationpage',
            constraint=models.UniqueConstraint(fields=('translation', 'page_number'), name='translation_pages_unique'),
        ),
    ]
