# Generated by Django 6.0.8 on 2026-08-07 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='archivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='nombre original')),
                ('extension', models.CharField(max_length=10, verbose_name='extensión')),
                ('mime_type', models.CharField(max_length=100, verbose_name='tipo MIME')),
                ('file_size', models.BigIntegerField(verbose_name='tamaño en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'deleted_at'], name='documents_user_deleted_idx'), models.Index(fields=['user', '-created_at'], name='documents_user_created_idx'), models.Index(fields=['original_name'], name='documents_original_name_idx')],
            },
        ),
    ]
