# Generated by Django 6.0.8 on 2026-08-07 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='última apertura'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', '-last_opened_at'], name='documents_user_opened_idx'),
        ),
    ]
